# Generated by Django 4.2.7 on 2026-02-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar_card', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('relation_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ward', models.CharField(blank=True, max_length=100, null=True)),
                ('gpu', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('coi', models.CharField(blank=True, max_length=100, null=True)),
                ('voter_id', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_number', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=15, null=True)),
                ('qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('home_category', models.CharField(blank=True, max_length=100, null=True)),
                ('professional_details', models.TextField(blank=True, null=True)),
                ('land_details', models.TextField(blank=True, null=True)),
                ('schemes_applied', models.TextField(blank=True, null=True)),
                ('health_status', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='name',
            name='name',
        ),
    ]
