# Generated by Django 4.2.7 on 2026-03-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_citizen_remove_name_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='relation_aadhaar',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='citizen',
            name='relation_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
