# Generated by Django 4.2.7 on 2026-03-10 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_citizen_relation_aadhaar_citizen_relation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='relation_type',
        ),
    ]
