# Generated by Django 4.2.7 on 2026-03-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_citizen_relation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='relation_name',
        ),
        migrations.AddField(
            model_name='citizen',
            name='relation_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
