# Generated by Django 4.2.7 on 2026-03-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_citizen_relation_name_citizen_relation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='assembly_constituency',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='citizen',
            name='bank_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='citizen',
            name='home_photograph',
            field=models.ImageField(blank=True, null=True, upload_to='home_photos/'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='rc_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
